### ISSUE TITLE
#US02#TK09 - Implementar la funcionalidad para poder visualizar los datos de la cuenta del usuario

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#116]
#26

**Comment by bit-rec98** [comment]
Se implementó la lógica para guardar parte de la información del usuario usando SharedPreferences para así utilizarla en un formulario habilitable que permite que el usuario pueda editar la información de su cuenta cuando lo requiera.

**Comment by junegrete** [comment]
Se realizaron ajustes para poder renderizar correctamente los cambios al editar el perfil del usuario.
