### ISSUE TITLE
#US02#TK11 - Configurar la funcionalidad para que el usuario pueda desactivar su cuenta cuando lo considere necesario desde la actividad "Editar Perfil"

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#118]
#26

**Comment by junegrete** [comment]
Se configuro la funcionalidad para desactivar la cuenta del  usuario.

**Comment by junegrete** [comment]
Se configuro la funcionalidad para desactivar la cuenta del  usuario.

**Comment by bit-rec98** [comment]
La funcionalidad para que el usuario pueda desactivar su cuenta está realizada y funciona correctamente.
