### ISSUE TITLE
#US03#TK02 - Añadir lógica de peticiones a base de datos para persistir los datos en la sección de productos

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#122]
#17

**Comment by MariaVictoria** [comment]
Estamos trabajando en la funcionalidad

**Comment by valentachini** [comment]
Se agrego la lógica necesaria para realizar peticiones a la base de datos, permitiendo la persistencia de datos en la sección de productos.
