### ISSUE TITLE
#US03#TK04 - Desarrollar la limitación de la navegación hacia el carro en caso de que el usuario no haya agregado productos

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#124]
#17

**Comment by MariaVictoria** [comment]
Estamos trabajando en la funcionalidad

**Comment by bit-rec98** [comment]
Se desarrolló la funcionalidad correctamente para evitar que el usuario no pueda avanzar más allá del carro si este no contiene productos.
