### ISSUE TITLE
#US04#TK01 - Desarrollar botón para eliminar ítems del carro

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#125]
#30

**Comment by bit-rec98** [comment]
Se desarrolló la funcionalidad descrita en el título de la issue de manera tal que al clickear en los botones que tienen un tacho de basura, los productos agregados al carro son eliminados del mismo.

**Comment by Js-Alvarez** [comment]
Se trabaja en el botón de eliminar sea un icono de basura y la su posición en el layout
