### ISSUE TITLE
#US04#TK03 - Desarrollar funcionalidad para poder gestionar la cantidad de ítems correspondiente a un producto que el cliente desea comprar con sus respectivas limitaciones 

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#127]
(no poder comprar 0 o menos productos y no poder comprar más productos que el stock disponible)

#30

**Comment by bit-rec98** [comment]
La funcionalidad de manipulación de cantidades de productos con las limitaciones de compra mínima que no sea menor a 1 ítem y máxima que no supere el stock existente está realizada.
