### ISSUE TITLE
#US08#TK01 - Añadir funcionalidad de barra de búsqueda de pedidos

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#136]
#41

**Comment by LautaroPena02** [comment]
Se realizo la funcionalidad de la barra de búsqueda por numero de pedido y también por fecha. Además se añadió un filtro para buscar los pedidos por estados ya sea para "Todos los estados", "Aceptado", "Pendiente" y "Cancelado".
