### ISSUE TITLE
#US08#TK02 - Añadir funcionalidad de renderizado dinámico de lista de pedidos para visualizarlos en la sección de un pedido particular

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#137]
Añadir funcionalidad de renderizado dinámico de lista de pedidos con ID y fecha en forma de botón para poder visualizarlos en la sección de un pedido particular

#41

**Comment by LautaroPena02** [comment]
En dashboard el cliente puede observar la lista de sus pedidos y puede seleccionarlos para verlos de manera particular.
