### ISSUE TITLE
#US10#TK03 - Desarrollar lógica para renderizar todos los pedidos 

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#163]
Desarrollar lógica para renderizar todos los pedidos en la pantalla de administrador
#159

**Comment by Alcario** [comment]
Se introdujeron mejoras significativas en el menú de navegación y la navegabilidad general de la aplicación. Los cambios principales incluyen:

Modificación del menú de navegación: Se ha rediseñado el menú para mejorar la accesibilidad y la experiencia del usuario.
Mejora de la navegabilidad: Se han optimizado las rutas y la estructura de la navegación para hacerla más intuitiva y eficiente

#170

**Comment by DenisseSabeff** [comment]
Ya subi codigo y cree una PR para que se revise el codigo.

**Comment by LautaroPena02** [comment]
Se logran renderizar todos los pedidos de los clientes en el dashboard administrador.
