### ISSUE TITLE
#US03 - "como usuario quiero poder elegir los productos que me gustan para comprar de manera ágil"

### ISSUE THREAD

**Issue by Alcario** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#17]
Criterios de aceptación:
- Los productos están expuestos en la sección de productos de manera categorizada según su correspondiente país.
- El usuario observa los productos de determinado país al hacer “tap” en el botón correspondiente a cualquiera de los países expuestos.
- Luego de haber tapeado en cualquiera de los botones correspondiente a un país, el usuario puede observar los productos en forma de tarjeta de forma organizada.
- Los detalles de los productos de un país elegido se exhiben en forma de tarjeta junto con un dropdown para seleccionar talles disponibles, cantidades y el botón para añadir tal producto al carro.
- El usuario elige obligatoriamente un talle disponible y una cantidad de un producto mayor a 1.
- Después de elegir un talle y una cantidad de determinado producto, el usuario puede agregar tal producto al carro al hacer click en el botón “Agregar al carro” y se le notifica que agregó tal producto seleccionado mediante un toast notificatorio.

**Comment by bit-rec98** [comment]
Desarrollo en progreso.

**Comment by valentachini** [comment]
Se ha implementado la funcionalidad que permite a los usuarios seleccionar y gestionar productos.
