### ISSUE TITLE
#US03#TK02 - Desarrollar e implementar  botón para redirección a sección de selección de país

### ISSUE THREAD

**Issue by Alcario** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#19]
#17

**Comment by junegrete** [comment]
se desarrollo e implementa los botones necesarios para cambio de seccion.

**Comment by DenisseSabeff** [comment]
esta issue se cierra en función a su objetivo correspondiente al sprint 1. Su funcionalidad se desarrollará en el sprint 2.
