### ISSUE TITLE
#US03#TK03 - Añadir lógica de peticiones a base de datos para persistir los datos en la sección de productos

### ISSUE THREAD

**Issue by Alcario** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#20]
#17

**Comment by bit-rec98** [comment]
Esta issue se va a cerrar para continuar trabajando sobre esta tarea pendiente en las nuevas issues correspondientes al sprint 2. Recordar vincular esta issue para documentar el inicio de la planificación.
