### ISSUE TITLE
#US03#TK04 - Añadir tarjeta con detalles de producto

### ISSUE THREAD

**Issue by Alcario** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#21]
#17

**Comment by bit-rec98** [comment]
Esta TK está parcialmente finalizada. Faltaría agregar el dropdown correspondiente (#24) para poder darle la estructura final a las tarjetas de los productos.

**Comment by bit-rec98** [comment]
Esta issue se va a cerrar para continuar trabajando sobre esta tarea pendiente en las nuevas issues correspondientes al sprint 2.
