### ISSUE TITLE
#US03#TK07 - Añadir selector de talle (dropdown)

### ISSUE THREAD

**Issue by Alcario** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#24]
#17

**Comment by bit-rec98** [comment]
Esta TK está parcialmente finalizada. Faltaría agregar el dropdown correspondiente en el componente de las tarjetas (#21) para poder darle la estructura final al componente de las tarjetas de los productos.

**Comment by bit-rec98** [comment]
Esta issue se va a cerrar para continuar trabajando sobre esta tarea pendiente en las nuevas issues correspondientes al sprint 2.
