### ISSUE TITLE
#US03#TK08 - Añadir selector de cantidad

### ISSUE THREAD

**Issue by Alcario** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#25]
#17

**Comment by bit-rec98** [comment]
Por cuestiones de usabilidad esta tarea no se va a desarrollar ya que es más conveniente y para no sobrecargar tanto la UI, realizar la selección de cantidad de productos que el usuario quiere comprar directamente en el carro de compras.
