### ISSUE TITLE
#SPRINT00#TK02 Rellenar bitácora registrando reuniones y avances del proyecto.

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#3]
#1 Registro de trabajo en la plataforma Canva.

**Comment by DenisseSabeff** [comment]
Está creado el documento en canva para registrar el trabajo del equipo y las respectivas reuniones.

**Comment by MariaVictoria** [comment]
Notificada, gracias
