### ISSUE TITLE
#US04 "Como usuario quiero poder eliminar productos que agregué al carrito, pero que no voy a comprar"

### ISSUE THREAD

**Issue by LautaroPena02** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#30]
Criterios de aceptación:

- Los productos seleccionados en la actividad de productos se pueden visualizar.
- El usuario accede a la actividad del carro.
- Los productos seleccionados en la actividad de productos se pueden visualizar con sus respectivos detalles en forma de tarjeta.
- Los productos agregados al carro se pueden eliminar en caso de no desear que estén añadidos. 
- El usuario puede eliminar los productos que se arrepiente de agregar al carrito de compras mediante un boton "eliminar".
- Se eliminará un producto al hacer "tap" en el botón correspondiente.
- Las tarjetas de cada producto contienen un selector de cantidades.
- El usuario cambia la cantidad de items correspondientes a un producto que está por comprar.
- La cantidad de productos se puede modificar directamente en el carro y esta no puede ser menor a 1 y mayor que el stock disponible.

**Comment by valentachini** [comment]
Queda pendiente el desarrollo del funcionamiento de los botones del carrito.

**Comment by Js-Alvarez** [comment]
Se logra crear la lógica para sumar, disminuir y eliminar productos
