### ISSUE TITLE
#SPRINT00#TK03 Github: Crear repositorio. Organizar kanban, Crear issues. Completar Wiki.Redactar las issues con su criterio de aceptación.

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#4]
#1

**Comment by MariaVictoria** [comment]
He realizado la actualización de la wiki.

**Comment by Alcario** [comment]
He completado la tarea "Crear issues" y redactaté las issues con su criterio de aceptación, correspondiente a la #US01 y #US03.

**Comment by bit-rec98** [comment]
Tareas realizadas: 
- Repositorio creado
- Tablero kanban y tablero de planning creados
- Esquema de ramas de desarrollo creado

**Comment by Js-Alvarez** [comment]
Se creo la #Us02 y sus respectiva 5 tareas.

**Comment by LautaroPena02** [comment]
He creado las issues US04 y US05 con sus criterios de aceptación y sus tareas correspondientes.

**Comment by toskamon** [comment]
Complete tarea de crear Issues y asignarle sus respectivas tareas, incluyendo los criterios de aceptación (#US07 y #US08)

**Comment by pabloscr** [comment]
He creado las issues #US09 y #US10 con sus criterios de aceptación y sus tareas correspondientes.

**Comment by MariaVictoria** [comment]
Queda actualizada la wiki.
