### ISSUE TITLE
#US04#TK03 - Desarrollar botón para finalizar compra. (Navegar a resumen de compra)

### ISSUE THREAD

**Issue by LautaroPena02** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#40]
#30

**Comment by valentachini** [comment]
El funcionamiento del botón para finalizar compra queda en desarrollo para el sprint 2.

**Comment by DenisseSabeff** [comment]
La funcionalidad se desarrollará en el sprint 2, por lo que se cierra la issue que corresponde al sprint 1.
