### ISSUE TITLE
#US05 "Como usuario registrado, quiero efectuar la compra de los artículos que seleccione y poder elegir el método de pago para poder abonarlos."

### ISSUE THREAD

**Issue by LautaroPena02** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#42]
Criterios de aceptación:

- Se puede observar el método de pago a elegir luego del ver el detalle de una compra.
- El usuario hace 'tap' en un botón con el texto "Pagar".
- Se despliega formulario para poder seleccionar su método de pago preferido para abonar los productos cargados en el carrito.
- El usuario registrado realiza la compra de los productos.
- El usuario hace 'tap' en un botón con el texto "Confirmar Pago".
- Se mostrará la opción de tres métodos de pago para abonar los productos cargados en el carrito de compras, completar el formulario de confirmación y abonar el monto total.

**Comment by bit-rec98** [comment]
La funcionalidad de compra de productos está realizada y funciona en condiciones.
