### ISSUE TITLE
#US08#TK03 -Por cada pedido particular mostrar un resumen con ID, estado, detalle, total pagado

### ISSUE THREAD

**Issue by toskamon** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#48]
#41

**Comment by MariaVictoria** [comment]
Dejo en el dashboard una lista de los pedidos realizados por el cliente , se muestra el id del pedido, y la fecha de su realización. para luego redirigirlo para mostrar detalle completo

**Comment by MariaVictoria** [comment]
se deja realizada la funcionalidad de direccionamiento al panel visual de "order" para los pedidos realizado por el cliente logueado

**Comment by LautaroPena02** [comment]
Panel visual de "Order" realizado para ver los detalles del pedido.
