### ISSUE TITLE
#US05#TK04 - Añadir formulario con detalles de método de pago

### ISSUE THREAD

**Issue by LautaroPena02** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#49]
#42

**Comment by toskamon** [comment]
en proceso para darle funcionalidad y se modifique de acuerdo al metodo de pago

**Comment by DenisseSabeff** [comment]
Se cierra issue que corresponde al sprint 1 ya que cumplió con los requerimientos planteados. Su funcionalidad de desarrollará en el sprint 2.
