### ISSUE TITLE
#US06#TK03 - Añadir botón para redirección a sección de contacto

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#56]
#53

**Comment by DenisseSabeff** [comment]
En proceso, está agregado el botón. Sigo trabajando la funcionalidad.

**Comment by DenisseSabeff** [comment]
Dejo funcionando el botón que redirecciona a la pantalla de contacto.

**Comment by MariaVictoria** [comment]
se agrega funcionalidad al botón de redireccionamiento a contacto en dashboard y en profile
