### ISSUE TITLE
#US09 "Como usuario quiero poder tener acceso intuitivo y centralizado del acceso a la gestión de pedidos"

### ISSUE THREAD

**Issue by pabloscr** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#58]
criterios de aceptación:
en relacion a accesos directos:

- La aplicación tiene una pantalla "Mi perfil".
- El usuario visualiza boton para ingresar a su dashboard y boton para cerrar sesión.
- Se mostrará el nombre del usuario, un boton para ingresar al dashboard y otro boton en rojo para finalizar la sesión.

**Comment by pabloscr** [comment]
criterios de aceptación: 
en relacion a consulta de pedidos/órdenes:
- El usuario inicia sesión en su cuenta y accede al panel de control
- El usuario inicia sesión completando los datos solicitados,  mediante click en "login", y podrá visualizar el panel de control 
- Se mostrara un panel de control de usuario donde podrá visualizar el historial de pedidos realizados por el usuario
en lo que hace a consulta de pedidos/órdenes:
- Se mostrara un panel de control de usuario donde podrá visualizar un resumen de compras con número de orden y datos del estado de su pedido 
en relacion a editar o eliminar un pedido confirmado y abonado: 
- El usuario inicia sesión y podrá mediante botones eliminar o editar su orden
- Se podrá visualizar un espacio de sugerencias de productos para el usuario a partir del historial de compras realizadas por el usuario.

**Comment by MariaVictoria** [comment]
Se implementa en "mi perfil" 3 botones literales con redireccionamiento : uno de dashboard, uno de conócenos, y el botón de finalizar sesión. 
Se muestra en "mi Perfil" el nombre completo del usuario, 
Me queda cambiar de color el botón de finalizar sesión

**Comment by MariaVictoria** [comment]
queda actualizado el color del botón Finalizar sesión y redireccionamiento a Login
