### ISSUE TITLE
#US09#TK01 -Añadir botón de navegación al dashboard de pedidos.

### ISSUE THREAD

**Issue by pabloscr** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#59]
#58

**Comment by pabloscr** [comment]
#58

**Comment by MariaVictoria** [comment]
en el dashboard de cliente quedaron añadidos los botones de navegación de menú, volver, inicio. productos, mi cuenta. y el de finalizar sesión

**Comment by MariaVictoria** [comment]
se aplica funcionalidad a los botones que quedaban
