### ISSUE TITLE
#SPRINT00#TK05 Completar historias de usuario y Tareas para el sprint backlog del sprint 1.

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#6]
#1 Completar Planilla de Historias de Usuario.

**Comment by Js-Alvarez** [comment]
Se comenzó a completar las historias de Usuarios, queda pendiente desde "Resumen de Compra" y queda pendiente también la asignación de tareas como la estimación de tiempo de cada tarea.

**Comment by Js-Alvarez** [comment]
Se termino de realizar las tareas en la planilla correspondiente

**Comment by junegrete** [comment]
Se definieron las historias de usuarios con sus respectivas tareas, quedado pendiente la asignación del o los responsable/s .

**Comment by valentachini** [comment]
Se agregaron al sprint backlog las task correspondientes a cada historia de usuario.
